### ISSUE TITLE
conan fails when running under haiku

### ISSUE THREAD

**Issue by eblanca** [emzeat/xdispatch2#5]
I'm trying to build xdispatch under haiku, so cloned xdispatch repository and installed conan 2.2.2 using pip, then also mz-cmaketools (into build/ ) but this is the fail:

![cmake_failure_due_to_conan_2 2 2_running_in_haiku](https://github.com/emzeat/xdispatch2/assets/1640886/bb47a899-dc62-4c64-bb89-1e66c4f5ae57)

It seems conan cannot detect the environment (it doesn't know anything about haiku) and stops.
Any hints?
(I know here you don't develop/fix conan, but maybe I can workaround this issue and do the build avoiding conan, or even fooling it)

**Comment by emzeat** [comment]
Yeah you would need to manually define a matching conan profile in build/Conan and update build/conan.cmake to pick it accordingly. I opted to not use Conan's auto detection but manually maintain the profiles.

Alternatively you can try disabling the inclusion of `conan.cmake` in [CMakeLists.txt:30](https://github.com/emzeat/xdispatch2/blob/dev/CMakeLists.txt#L30)

**Comment by emzeat** [comment]
Resolved by cba7f72:
* Will fall back to using the system default profile if unavailable
* conan is only enabled when configuring via `./build/generator.sh` compared to using CMake directly and can ultimately be controlled using cache variable `MZ_USE_CONAN`
